#!/usr/bin/env bash
#
# pkgconfig-shim.sh — generate pthread-free .pc files and print their directory.
#
# SwiftPM parses .pc files with its own parser and rejects flags outside an allowlist, warning
# "prohibited flag(s): -pthread" once per system-library target whenever the build plan is
# regenerated. The flag arrives transitively (glib-2.0 -> Requires.private: sysprof-capture-4,
# which carries `-pthread` in its Cflags), so it is not ours to remove at the source.
#
# SwiftPM *discards* the flag and builds fine, so this is pure noise — which means stripping it in a
# shim is behaviour-preserving by construction: it pre-removes exactly what SwiftPM already drops.
#
# The shim is GENERATED, never committed: .pc contents are machine-specific (Debian multiarch paths
# differ from Arch, and which .pc files carry -pthread varies by distro and glib version). It also
# inlines the fully-resolved flags with NO `Requires:` line — keeping one makes SwiftPM re-expand it
# against the real system files and pick -pthread straight back up.
#
# Usage:  PKG_CONFIG_PATH="$(scripts/pkgconfig-shim.sh)" swift build
set -euo pipefail
cd "$(dirname "$0")/.."

DIR="${1:-.build/pkgconfig}"

# Only the packages Package.swift names as `pkgConfig:`.
PACKAGES=(appindicator3-0.1 libnotify zlib sqlite3)

# No pkg-config (or not Linux) means nothing to shim. Print nothing so callers fall back to the
# unmodified environment rather than pointing PKG_CONFIG_PATH at an empty directory.
command -v pkg-config >/dev/null 2>&1 || exit 0

mkdir -p "$DIR"

for pkg in "${PACKAGES[@]}"; do
  # A missing package must not produce an empty .pc — that would SHADOW the real one and break the
  # build outright. Skip it and let pkg-config find the system copy.
  pkg-config --exists "$pkg" 2>/dev/null || continue

  version=$(pkg-config --modversion "$pkg" 2>/dev/null || echo "0")
  # Keep only what SwiftPM accepts: include dirs, library dirs, libraries.
  # `|| true`: a package with headers on the default path (zlib) legitimately has no -I flags, and
  # grep exiting 1 on no-match would otherwise kill the script under `set -e`.
  cflags=$(pkg-config --cflags "$pkg" | tr ' ' '\n' | grep -E '^-I' | tr '\n' ' ' || true)
  libs=$(pkg-config --libs "$pkg" | tr ' ' '\n' | grep -E '^-(L|l)' | tr '\n' ' ' || true)

  tmp="$DIR/.$pkg.pc.tmp"
  {
    echo "# Generated by scripts/pkgconfig-shim.sh — do not edit, do not commit."
    echo "# Flags are inlined and pthread-free; no Requires: line (see the script's header)."
    echo "Name: $pkg"
    echo "Description: pthread-free shim for $pkg"
    echo "Version: $version"
    echo "Cflags: $cflags"
    echo "Libs: $libs"
  } > "$tmp"

  # Only replace when the content actually changed — an unchanged mtime keeps SwiftPM's cached
  # build plan valid, so regenerating on every make invocation costs nothing.
  if [[ -f "$DIR/$pkg.pc" ]] && cmp -s "$tmp" "$DIR/$pkg.pc"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$DIR/$pkg.pc"
  fi
done

echo "$(cd "$DIR" && pwd)"
